# Generated by Django 3.0.6 on 2020-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_task', models.CharField(max_length=200)),
                ('completion_date', models.DateTimeField(verbose_name='date_of_completion')),
            ],
        ),
    ]
