# Generated by Django 3.0.6 on 2020-05-11 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListApp', '0002_donetasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(choices=[('0', 'low'), ('1', 'moderate'), ('2', 'high')], default=datetime.datetime(2020, 5, 11, 7, 42, 9, 782149, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
