# Generated by Django 3.0.6 on 2020-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoListApp', '0005_auto_20200511_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='priority',
            field=models.CharField(choices=[('0', 'low'), ('1', 'moderate'), ('2', 'high')], max_length=10, null=True),
        ),
    ]
